# Generated by Django 4.2.2 on 2023-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0006_remove_pdffile_annotated_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('pdf_data', models.TextField()),
            ],
        ),
    ]
